### PR TITLE
Initialize 11.0 branch

### PR DESCRIPTION
**Pull request by Katulos**
I am an active user of Odoo 11, due to a number of circumstances.

Since the author no longer maintains the [repository](https://github.com/codup/odoo-ru/tree/11.0), I decided to try moving it to OCA

### CODE REVIEW

**Comment by em230418** [comment]
Hi, @pedrobaeza! Could you please create empty 11.0 branch? I don't think github users other than OCA maintainers can do this.

**Comment by pedrobaeza** [comment]
Although a bit old... I have initialized it: https://github.com/OCA/l10n-russia/tree/11.0

**Comment by okuryan** [comment]
@Katulos please, make a merge request for 11.0

**Comment by pedrobaeza** [comment]
And one module per PR.

**Pull request closed without merging**
